.TH TINCOIN-CLI "1" "June 2016" "tincoin-cli 0.12"
.SH NAME
tincoin-cli \- a remote procedure call client for Tincoin Core. 
.SH SYNOPSIS
tincoin-cli [options] <command> [params] \- Send command to Tincoin Core. 
.TP
tincoin-cli [options] help \- Asks Tincoin Core for a list of supported commands.
.SH DESCRIPTION
This manual page documents the tincoin-cli program. tincoin-cli is an RPC client used to send commands to Tincoin Core.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

.SH "SEE ALSO"
\fBtincoind\fP, \fBtincoin.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
